### ISSUE TITLE
No nodes listed

### ISSUE THREAD

**Issue by Sabicool** [publicimageltd/delve#10]
I am using Doom Emacs, and have my config.el file as below:

```
(use-package! lister)
(use-package! delve
  :bind
  (("<f11>" . delve))
  :config
  ;; set meaningful tag names for the dashboard query
  (setq delve-dashboard-tags '("dashboard" "index"))
  ;; turn on delve-minor-mode when org roam file is opened:
  (delve-global-minor-mode))
```

Unfortunately when I run Delve, it doesn't show any entries:
![Screenshot from 2022-02-23 13-59-01](https://user-images.githubusercontent.com/43723884/155268856-0cd8c3a9-3231-4b9d-b89f-e667958c12cb.png)

**Comment by publicimageltd** [comment]
I don't quite understand the problem. Per default, the dashboard has no distinct nodes, but only those queries which I can also see on the screenshot. What happens if you "open" the queries by pressing <TAB> when the cursor is on the line? If =doom= somehow blocks this key, try to call it explicitly: =M-x delve--key--tab=. Are there any nodes then?

**Comment by publicimageltd** [comment]
BTW, there should be no need to explicitly require `lister`. Since it is on MELPA, it should be downloaded by the package manager automatically.

**Comment by Sabicool** [comment]
Thank you, this solves the issue

**Comment by publicimageltd** [comment]
You're welcome! Please tell me if the problem has been that `doom` somehow shadows the `<TAB>` key, or if the problem had something to do with `doom`s keys in general. I should then add that to the README.

**Comment by Sabicool** [comment]
It was an issue with the Doom keys
