### ISSUE TITLE
upgrade to org roam v2

### ISSUE THREAD

**Issue by BobCromwell** [publicimageltd/delve#6]
org roam v2 has released. Will this repo upgrade to be compitable with v2?

**Comment by publicimageltd** [comment]
Thanks for pinging!

There will be a new version, but its not going to be a simple update. The new node system multiplies the number of nodes returned and challenges the existing concept, both in terms of usability (500+ results for a query), and in terms of performance (500 items in a buffer slows the current UI down). So I am planning on introducing a new variant, not just a simply upgrade; and possibly integrating it with `org-roam-ui`. 

Things are also slowing down because I was pointed to an alternative way to do the list editing (the "ewoc" library), and that seems to be a solution for the performance issue, which I want to test before writing delve v2.

Saying all this, I feel it might be wise to just adopt the queries for the beginning, so that Delve remains usable. We'll see, I can't promise much right now since RL keeps me busy, and I've not so much time for Elisp hacking right now...

**Comment by publicimageltd** [comment]
Just to keep you posted: I am close to done with rewriting Lister, the basis of Delve. Now I can turn to finally add v2 support.  Stay tuned!

**Comment by publicimageltd** [comment]
New version is out now. Thanks for your patience.

**Comment by oatmealm** [comment]
Great news. Congratz! 
Testing. Will report as I go along.
